# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', type: 'nfs'

  # Vmware.
  config.vm.define "vmware" do |vmware|
    vmware.vm.hostname = "vmware-centos7"
    vmware.vm.box = "file://builds/vmware-centos7.box"
    vmware.vm.network :private_network, ip: "172.16.3.2"

    config.vm.provider :vmware do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.provision "shell", inline: "echo Hello, World"
  end

end
